### ISSUE TITLE
Хм, я над этим подумаю, изначально у меня было, что-то типа component.ItemId = LiveDataElement.id, по факту одно и тоже, да, ты прав, просто я думала изнчально сделать приватный id, поэтому оно было, в принципе можно и удалить, можно и оставить погоды не сделает)

### ISSUE THREAD

**Issue by hekkaaa** [hekkaaa/uml-drawing#38]
Хм, я над этим подумаю, изначально у меня было, что-то типа component.ItemId = LiveDataElement.id, по факту одно и тоже, да, ты прав, просто я думала изнчально сделать приватный id, поэтому оно было, в принципе можно и удалить, можно и оставить погоды не сделает)

_Originally posted by @pira9ha in https://github.com/hekkaaa/uml-drawing/pull/36#discussion_r757881521_

**Comment by pira9ha** [comment]
Исправила ранее
