### ISSUE TITLE
Починить баг при создании файла проекта из GUI.

### ISSUE THREAD

**Issue by hekkaaa** [hekkaaa/uml-drawing#66]

**Comment by hekkaaa** [comment]
![Uploading Снимок экрана 2021-11-30 214250.png…]()

**Comment by hekkaaa** [comment]
![Снимок экрана 2021-11-30 214251](https://user-images.githubusercontent.com/46771781/144108437-bc0831a5-fba5-46b8-b152-680dc13821e8.png)

**Comment by hekkaaa** [comment]
Стреляет от  **string json = JsonSerializer.Serialize(obj.ListObjectFigure);**

**Comment by hekkaaa** [comment]
ответ тут https://question-it.com/questions/3163226/ne-udalos-zagruzit-systemthreadingtasksextensions
пакет System.Threading.Tasks.Extensions отсутствовал на GUI. Установил. В **Logical** не ставил, может стрельнуть от туда.
@pira9ha  АЛИИИИИИИИИИИИИЯЯЯ! Это все твой Framework 4.7)

**Comment by pira9ha** [comment]
Прости(((
