### ISSUE TITLE
Прикрутить методы Логики к кнопкам Create и Load Project

### ISSUE THREAD

**Issue by hekkaaa** [hekkaaa/uml-drawing#70]

**Comment by hekkaaa** [comment]
Требуется доработка метода на твоей стороне @pira9ha 

При вызове исполнении такого кода:
```
   Handler btnclick = new Handler();
            btnclick.LoadProject();
            Close();
```

Получаем отвал жопы:

![Снимок экрана 2021-12-01 181259](https://user-images.githubusercontent.com/46771781/144260701-4db8d74f-34de-4bb1-9dcf-27de57a4aa32.png)

**Comment by hekkaaa** [comment]
Просто добавь `string name` в свой метод  и передай его  дальше в мое API  вместо `_live.Data.nameproject`

**Comment by pira9ha** [comment]
исправила, воть
![image](https://user-images.githubusercontent.com/67172139/144317968-1a927c04-04e6-44dd-84c7-ecdf5f04a601.png)

**Comment by pira9ha** [comment]
Так?

**Comment by hekkaaa** [comment]
> Так?

Yes. Where Pull Requests? Next time?

**Comment by pira9ha** [comment]
Да сча могу
