### ISSUE TITLE
Баг с загрузкой объектов

### ISSUE THREAD

**Issue by hekkaaa** [hekkaaa/uml-drawing#98]
1. Создать новый проект.
2. обозвать его как то
3.  добавить все 3 элемента (квадратов) на полотно.
4.  Изменить текст внутри каждого квадрата и поля.
5. сохранить проект.
6. Закрыть программу.
7. открыть вновь и загрузить проект по имени "см пункт 2"
8.  
![Снимок экрана 2021-12-08 052804](https://user-images.githubusercontent.com/46771781/145137573-ff214106-9ff4-48a9-b009-2120cac8512c.png)

**Comment by pira9ha** [comment]
да, увидела баг, у меня тоже так. Ну уже неважно)

**Comment by hekkaaa** [comment]
Исправленно.
Done.
